//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace frecevents.web
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventInfo
    {
        public EventInfo()
        {
            this.Registrations = new HashSet<Registration>();
        }
    
        public string ID { get; set; }
        public string Title { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public System.DateTime EndDateTime { get; set; }
        public string EventType { get; set; }
        public string EventSite { get; set; }
        public string Description { get; set; }
        public string SiteURL { get; set; }
        public string SiteAddress { get; set; }
        public string MapURL { get; set; }
        public string Notes { get; set; }
        public bool Trailers { get; set; }
        public bool Lodging { get; set; }
    
        public virtual ICollection<Registration> Registrations { get; set; }
    }
}
