//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace frecevents.web
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class freceventsEntities : DbContext
    {
        public freceventsEntities()
            : base("name=freceventsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EventInfo> EventInfoes { get; set; }
        public virtual DbSet<Registration> Registrations { get; set; }
        public virtual DbSet<Rider> Riders { get; set; }
        public virtual DbSet<Event> Events { get; set; }
    }
}
