//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace frecevents.web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rider
    {
        public Rider()
        {
            this.Registrations = new HashSet<Registration>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Notes { get; set; }
        public int Trailerspace { get; set; }
        public bool FoodVolunteer { get; set; }
        public short RegistrationRequest { get; set; }
        public int Lodgingspace { get; set; }
    
        public virtual ICollection<Registration> Registrations { get; set; }
    }
}
